{
 "title": "Topics",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Instant", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mqtt_topic_float64_value{topic=~\".*temperature.*/get\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Circumstances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mqtt_topic_float64_value{topic=~\".*circumstances/(.*_sunrise.*|.*_sunset.*|.*_waketime|.*_bedtime|cold|hot)/get\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Presence",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mqtt_topic_float64_value{topic=~\".*arp.*/get|.*presence.*/get\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Heater",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mqtt_topic_float64_value{topic=~\".*heater.*/get\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Aircon",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mqtt_topic_float64_value{topic=~\".*aircon.*/get\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Sprinklers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mqtt_topic_float64_value{topic=~\".*sprinklers.*get\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Lights",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mqtt_topic_float64_value{topic=~\".*lights.*/get|.*switches/globe.*/get\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Sensors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "mqtt_topic_float64_value{topic=~\".*temperature.*/get\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Circumstances",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "mqtt_topic_float64_value{topic=~\".*circumstances/(.*_sunrise.*|.*_sunset.*|.*_waketime|.*_bedtime|cold|hot)/get\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Presence",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "mqtt_topic_float64_value{topic=~\".*arp.*/get|.*presence.*/get\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Devices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Aircon",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mqtt_topic_float64_value{topic=~\".*request/aircon.*\"}",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "mqtt_topic_float64_value{topic=~\".*aircon.*/set\"}",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "mqtt_topic_float64_value{topic=~\".*aircon.*/get\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Heater ",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mqtt_topic_float64_value{topic=~\".*request/heater.*\"}",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "mqtt_topic_float64_value{topic=~\".*heater.*/set\"}",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "mqtt_topic_float64_value{topic=~\".*heater.*/get\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Sprinklers ",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mqtt_topic_float64_value{topic=~\".*request/heater.*\"}",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "mqtt_topic_float64_value{topic=~\".*sprinklers.*set\"}",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "mqtt_topic_float64_value{topic=~\".*sprinklers.*get\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Lights",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mqtt_topic_float64_value{topic=~\".*request/lights.*\"}",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "mqtt_topic_float64_value{topic=~\".*lights.*/set|.*switches/globe.*/set\"}",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "mqtt_topic_float64_value{topic=~\".*lights.*/get|.*switches/globe.*/get\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Decisions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Toggling Aircon",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "mqtt_topic_float64_value{topic=\"home/outside/weather/temperature/get\"}",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "mqtt_topic_float64_value{topic=\"home/circumstances/hot/get\"} * 5",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "mqtt_topic_float64_value{topic=\"home/request/aircons/fujitsu\"} * 10"
    },
    {
     "expr": "mqtt_topic_float64_value{topic=\"home/request/aircons/mitsubishi\"} * 15"
    }
   ]
  },
  {
   "title": "Toggling Heater",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "mqtt_topic_float64_value{topic=\"home/outside/weather/temperature/get\"}",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "mqtt_topic_float64_value{topic=\"home/circumstances/cold/get\"} * 5",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "mqtt_topic_float64_value{topic=\"home/inside/heater/state/get\"} * 10",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Toggling Sprinklers",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "mqtt_topic_float64_value{topic=\"home/outside/weather/temperature/get\"}",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "mqtt_topic_float64_value{topic=\"home/outside/weather/humidity/get\"}",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "mqtt_topic_float64_value{topic=\"home/outside/weather/pressure/get\"} / 10",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "mqtt_topic_float64_value{topic=~\".*sprinklers.*get\"} * 10"
    }
   ]
  },
  {
   "title": "Toggling Lights",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "mqtt_topic_float64_value{topic=\"home/circumstances/after_sunset_15m_early/get\"}",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "mqtt_topic_float64_value{topic=~\".*request/light.*\"} * 5",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "mqtt_topic_float64_value{topic=~\".*request/switch.*\"} * 10",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}