---
apiVersion: v1
kind: Service
metadata:
  namespace: mqtt-things
  name: mqtt-broker
spec:
  ports:
    - protocol: TCP
      port: 1883
      targetPort: 1883
---
apiVersion: v1
kind: Endpoints
metadata:
  namespace: mqtt-things
  name: mqtt-broker
subsets:
  - addresses:
      - ip: 192.168.137.253
    ports:
      - port: 1883
